"""make name and age nullable

Revision ID: 0b364b8f3a07
Revises: b981c85bd817
Create Date: 2025-07-21 16:21:19.929456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b364b8f3a07'
down_revision: Union[str, Sequence[str], None] = 'b981c85bd817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('people', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('people', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
