"""create table Message

Revision ID: 4538cb1ee008
Revises: 0b364b8f3a07
Create Date: 2025-08-01 22:46:54.786316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4538cb1ee008'
down_revision: Union[str, Sequence[str], None] = '0b364b8f3a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('msgid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('msg', sa.String(length=369), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('msgid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
